
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAllowedRepos
metadata:
  name: repo-is-openpolicyagent
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Pod" , "Deployment"]
    namespaces:
      - "default"
  parameters:
    repos:
      - "openpolicyagent/"
      
